version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - proxy_net

  service1:
    build:
      context: ./service_1
    expose:
      - "8001"
    networks:
      - proxy_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 10s
      timeout: 5s
      retries: 3

  service2:
    build:
      context: ./service_2
    expose:
      - "8002"
    networks:
      - proxy_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  proxy_net:
    driver: bridge
